[tool.poetry]
name = "glacier-flow-model"
version = "0.1.0"
description = "Modeling glaciers flow, grounded on the glaciers mass balance and a digital elevation model (DEM)."
maintainers = [
    "Merlin Unterfinger <info@munterfinger.ch>",
    "Manuel Luck <admin@geoluck.ch>"
]
authors = ["Merlin Unterfinger <info@munterfinger.ch>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/munterfinger/glacier-flow-model"

[tool.poetry.dependencies]
python = "^3.8"
scipy = "^1.5.2"
numpy = "^1.19.2"
GDAL = "^3.1.3"
matplotlib = "^3.3.2"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
mypy = "^0.782"
Sphinx = "^3.2.1"
flake8 = "^3.8.4"
tomlkit = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
