[tool.poetry]
name = "glacier-flow-model"
version = "0.1.2"
description = "Modeling glaciers flow, grounded on the glaciers mass balance and a digital elevation model (DEM)."
maintainers = ["Merlin Unterfinger <info@munterfinger.ch>"]
authors = [
    "Merlin Unterfinger <info@munterfinger.ch>",
    "Manuel Luck <admin@geoluck.ch>"]
license = "MIT"
readme = "README.rst"
homepage = "https://pypi.org/project/glacier-flow-model/"
documentation = "https://glacier-flow-model.readthedocs.io/en/latest/"
repository = "https://github.com/munterfi/glacier-flow-model"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = "^1.8.0"
numpy = "^1.22.2"
GDAL = "^3.4.1"
matplotlib = "^3.5.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
mypy = "^0.940"
Sphinx = "^4.4.0"
flake8 = "^4.0.1"
tomlkit = "^0.10.0"
codecov = "^2.1.12"
pydata-sphinx-theme = "^0.8.0"
black = {version = "^22.1.0", allow-prereleases = true}

[tool.mypy]
ignore_missing_imports = true
exclude = ["^docs\\/source\\/conf\\.py$"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
